### ISSUE TITLE
Error al iniciar el index.php

### ISSUE THREAD

**Issue by morfeo777** [Uala-Developers/ualabis-php#5]
Cuando inicio el index.php me aparece este error:

SDK TESTS

Fatal error: Uncaught Uala\Error: Unknown error in C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\src\SDK\HttpRequest.php:47 Stack trace: #0 C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\src\SDK\HttpRequest.php(69): Uala\HttpRequest::execute(Object(CurlHandle)) #1 C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\src\SDK\SDK.php(68): Uala\HttpRequest::post('https://auth.st...', Array) #2 C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\src\SDK\SDK.php(53): Uala\SDK->createAccessToken() #3 C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\examples\index.php(46): Uala\SDK->__construct('terrestreapp', 'g3JGxHNrzTkA2z7...', 'ZZtAt0JFKwCzksU...', true) #4 {main} thrown in C:\xampp\htdocs\VisualUpload5\dist\Uala\ualabis-php\src\SDK\HttpRequest.php on line 47

**Comment by pabloUALA-BIS** [comment]
Hola @morfeo777, como estas? el error por lo que puedo ver, es por pasar mal las credenciales al constructor. 

Fijate de aplicar credenciales validas de ambientes bajos (las mismas las podes ver desde la [web de Ualá](https://web.uala.com.ar/login) en el apartado de Cobros, como tambien desde cualquier dispositivo iOS)

De continuar el error hacérmelo saber y vemos como ayudarte.

Saludos!
