### ISSUE TITLE
Create order a veces retorna un objeto vacio stdClass

### ISSUE THREAD

**Issue by rsmaximiliano** [Uala-Developers/ualabis-php#6]
Hola, quería saber cual es el motivo de que a veces cuando llamo para crear una orden, $this->sdk->createOrder(), a veces retorna un objeto vacio stdClass y a veces retorna la orden con éxito.

**Comment by pabloUALA-BIS** [comment]
Hola @rsmaximiliano, podes dar un poco mas de contexto con ejemplos que podamos usar para poder replicar lo que comentas? por lo menos desde nuestro lado no vemos ese tipo de comportamiento. Quedamos atentos!
